name: Test

on:
  push:
  pull_request:

env:
  JAVA_OPTS: ${{ vars.JAVA_OPTS }}

jobs:
  jvm:
    name: Test JVM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Test
        run: ./mill --no-server jvm.test

  native:
    name: Test Native
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Test
        run: ./mill --no-server native.test

  js:
    name: Compile JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Compile
        run: ./mill --no-server js.compile
